#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# ADD-JVB-NODE
# ------------------------------------------------------------------------------
# Add an additional Jitsi videobridge2 node to the cluster.
#
# Usage:
#     add-jvb-node <NODE-ADDRESS>
# ------------------------------------------------------------------------------
SSH_CONFIG="/root/.ssh/jms-config"

APP="nordeck-jvb"
APP_REPO="ssh://git@github.com:22/nordeck/bullseye-lxc-jitsi.git"
INSTALLER="https://raw.githubusercontent.com/nordeck/bullseye-lxc-base/main/installer/ni"
NODE=$1

JITSI_ROOTFS="/var/lib/lxc/nordeck-jitsi/rootfs"
JVB_ROOTFS="/var/lib/lxc/nordeck-jvb/rootfs"

ssh_() {
    ssh -F $SSH_CONFIG $NODE -- "$@"
}

scp_() {
    scp -F $SSH_CONFIG $1 $NODE:$2
}


# ------------------------------------------------------------------------------
# trap on exit
# ------------------------------------------------------------------------------
function on_exit {
    if [[ "$COMPLETED" != true ]]; then
        cat <<EOF

Something went wrong. The installation couldn't be completed!
EOF
        exit 1
    else
        cat <<EOF

Completed successfully!
EOF
        exit 0
    fi
}

COMPLETED=false
trap on_exit EXIT

if [[ -z "$NODE" ]]; then
    cat <<EOF
Usage:
       add-jvb-node <NODE-ADDRESS>
EOF
    exit 1
fi


# ------------------------------------------------------------------------------
# exports
# ------------------------------------------------------------------------------
JITSI_FQDN=$(cat $JITSI_ROOTFS/root/meta/jitsi-fqdn || true)
JVB_SHARD_PASSWD=$(cat $JITSI_ROOTFS/root/meta/jvb-shard-passwd || true)
JVB_VERSION=$(cat $JITSI_ROOTFS/root/meta/jvb-version || true)


# ------------------------------------------------------------------------------
# installation
# ------------------------------------------------------------------------------
ssh_ <<EOS
set -e
apt-get -y --allow-releaseinfo-change update
apt-get -y install wget
wget $INSTALLER -O /tmp/ni -T 30
EOS

scp_ /root/.ssh/deploy.key /root/.ssh/

ssh_ <<EOS
set -e
export APP_REPO=$APP_REPO
export JITSI_FQDN=$JITSI_FQDN
export JVB_VERSION=$JVB_VERSION
export JVB_SHARD_PASSWD=$JVB_SHARD_PASSWD
export DONT_RUN_HOST_CUSTOM_CA=true
export APT_PROXY=$APT_PROXY

cd /tmp
bash ni $APP || (rm -f /root/.ssh/deploy.key; false)
rm -f /root/.ssh/deploy.key
EOS


# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
COMPLETED=true
