#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# ADD-JVB-NODE
# ------------------------------------------------------------------------------
# Add an additional Jitsi videobridge2 node to the cluster.
#
# Usage:
#     add-jvb-node <NODE-ADDRESS>
# ------------------------------------------------------------------------------
NODE=$1
SSH_CONFIG="/root/.ssh/jms-config"
INSTALLER="https://raw.githubusercontent.com/nordeck/bullseye-lxc-base/main/installer/ni"
APP_REPO="ssh://git@github.com:22/nordeck/bullseye-lxc-jitsi.git"
APP_CONFIG="nordeck-jvb.conf"
JITSI_ROOTFS="/var/lib/lxc/nordeck-jitsi/rootfs"
JVB_ROOTFS="/var/lib/lxc/nordeck-jvb/rootfs"

ssh_() {
    ssh -F $SSH_CONFIG $NODE -- "$@"
}

scp_() {
    scp -F $SSH_CONFIG $1 $NODE:$2
}


# ------------------------------------------------------------------------------
# trap on exit
# ------------------------------------------------------------------------------
function on_exit {
    if [[ "$COMPLETED" != true ]]; then
        cat <<EOF

Something went wrong. The installation couldn't be completed!
EOF
        exit 1
    else
        cat <<EOF

Completed successfully!
EOF
        exit 0
    fi
}

COMPLETED=false
trap on_exit EXIT

if [[ -z "$NODE" ]]; then
    cat <<EOF
Usage:
       add-jvb-node <NODE-ADDRESS>
EOF
    exit 1
fi


# ------------------------------------------------------------------------------
# cluster related parameters
# ------------------------------------------------------------------------------
JITSI_FQDN=$(egrep '^JVB_HOSTNAME=' $JITSI_ROOTFS/etc/jitsi/videobridge/config | \
             cut -d '=' -f2)
JVB_SECRET=$(egrep '^JVB_SECRET=' $JITSI_ROOTFS/etc/jitsi/videobridge/config | \
             cut -d '=' -f2)
SHARD_PASSWD=$(egrep '^org.jitsi.videobridge.xmpp.user.shard.PASSWORD' \
    $JITSI_ROOTFS/etc/jitsi/videobridge/sip-communicator.properties | \
    cut -d '=' -f2)
JVB_VERSION=$(cat $JITSI_ROOTFS/root/meta/jvb-version || true)
EXTERNAL_IP=$(dig -4 +short myip.opendns.com a @resolver1.opendns.com)


# ------------------------------------------------------------------------------
# repository
# ------------------------------------------------------------------------------
if [[ ! -f "/tmp/app-repo/installer/$APP_CONFIG" ]]; then
    rm -rf /tmp/app-repo
    git clone --depth=1 $APP_REPO /tmp/app-repo \
        --config core.sshCommand="ssh \
            -i /root/.ssh/deploy.key \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null"
fi

# ------------------------------------------------------------------------------
# installation
# ------------------------------------------------------------------------------
ssh_ <<EOS
set -e
apt-get -y --allow-releaseinfo-change update
apt-get -y install wget
wget $INSTALLER -O /tmp/ni -T 30
EOS

scp_ /tmp/app-repo/installer/$APP_CONFIG /tmp/$APP_CONFIG
scp_ /root/.ssh/deploy.key /root/.ssh/

ssh_ <<EOS
set -e
export JITSI_FQDN=$JITSI_FQDN
export JVB_VERSION=$JVB_VERSION

cd /tmp
bash ni $APP_CONFIG || (rm -f /root/.ssh/deploy.key; false)
rm -f /root/.ssh/deploy.key

sed -i 's/shard.HOSTNAME=.*/shard.HOSTNAME=$JITSI_FQDN/' \
    $JVB_ROOTFS/etc/jitsi/videobridge/sip-communicator.properties
sed -i 's/shard.PASSWORD=.*/shard.PASSWORD=$SHARD_PASSWD/' \
    $JVB_ROOTFS/etc/jitsi/videobridge/sip-communicator.properties
sed -i 's/^JVB_SECRET=.*/JVB_SECRET=$JVB_SECRET/' \
    $JVB_ROOTFS/etc/jitsi/videobridge/config
EOS

[[ -n "$(ssh_ dig +short $JITSI_FQDN)" ]] || \
    ssh_ "echo '$EXTERNAL_IP $JITSI_FQDN' >> $JVB_ROOTFS/etc/hosts"

ssh_ lxc-attach -n nordeck-jvb systemctl stop jitsi-videobridge2.service
ssh_ lxc-attach -n nordeck-jvb systemctl start jitsi-videobridge2.service


# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
COMPLETED=true
