#!/bin/bash
set -e

# ------------------------------------------------------------------------------
# UPDATE-SIP-CONFIG
# ------------------------------------------------------------------------------
# Update PJSUA configuration on an additional video-sip-gateway node.
#
# Usage:
#     update-sip-config <NODE-ADDRESS>
# ------------------------------------------------------------------------------
SSH_CONFIG="/root/.ssh/jms-config"

NODE=$1

JITSI_ROOTFS="/var/lib/lxc/nordeck-jitsi/rootfs"
SIP_ROOTFS="/var/lib/lxc/nordeck-sip-template/rootfs"

ssh_() {
    ssh -F $SSH_CONFIG $NODE -- "$@"
}

scp_() {
    scp -F $SSH_CONFIG $1 $NODE:$2
}


# ------------------------------------------------------------------------------
# trap on exit
# ------------------------------------------------------------------------------
function on_exit {
    if [[ "$COMPLETED" != true ]]; then
        cat <<EOF

Something went wrong. The installation couldn't be completed!
EOF
        exit 1
    else
        cat <<EOF

Completed successfully!
EOF
        exit 0
    fi
}

COMPLETED=false
trap on_exit EXIT

if [[ -z "$NODE" ]]; then
    cat <<EOF
Usage:
       update-sip-config <NODE-ADDRESS>
EOF
    exit 1
fi


# ------------------------------------------------------------------------------
# uploads
# ------------------------------------------------------------------------------
ssh_ "rm -f /root/pjsua.config"
if [[ -f $JITSI_ROOTFS/root/meta/pjsua.config ]]; then
    scp_ $JITSI_ROOTFS/root/meta/pjsua.config /root/
fi

ssh_ "rm -f /root/env.sidecar"
if [[ -f "$JITSI_ROOTFS/root/meta/env.sidecar.sip" ]]; then
    scp_ $JITSI_ROOTFS/root/meta/env.sidecar.sip /root/env.sidecar
fi


# ------------------------------------------------------------------------------
# update
# ------------------------------------------------------------------------------
ssh_ <<EOS
set -e

if [[ -f /root/pjsua.config ]]; then
    cp /root/pjsua.config $SIP_ROOTFS/etc/jitsi/jibri/
    rm -f /root/pjsua.config
fi

if [[ -f /root/env.sidecar ]]; then
    cp /root/env.sidecar $SIP_ROOTFS/etc/jitsi/sidecar/env
    rm -f /root/env.sidecar
fi

systemctl stop sip-ephemeral-container.service
systemctl start sip-ephemeral-container.service
EOS


# ------------------------------------------------------------------------------
# completed
# ------------------------------------------------------------------------------
COMPLETED=true
