#!/bin/bash

sed -i "/^org.jitsi.videobridge.xmpp.user.shard.MUC_NICKNAME=/ \
     s/=.*/=$(uuidgen)/" /etc/jitsi/videobridge/sip-communicator.properties

EXTERNAL_IP=$(dig -4 +short myip.opendns.com a @resolver1.opendns.com) || true
if [[ -n "$EXTERNAL_IP" ]]; then
    hocon -f /etc/jitsi/videobridge/jvb.conf \
        set videobridge.websockets.server-id "\"$EXTERNAL_IP\""
fi
