#!/usr/bin/bash

# ------------------------------------------------------------------------------
# JIBRI-EPHEMERAL-STOP
# ------------------------------------------------------------------------------
#
# Stop the ephemeral Jibri containers.
#
# ------------------------------------------------------------------------------
lxc-autostart -s -g nordeck-jibri -t 30
lxc-autostart -k -g nordeck-jibri

for i in $(seq 10); do
    sleep 1
    [[ -z "$(lxc-ls -1g nordeck-jibri | grep -v nordeck-jibri-template)" ]] && \
        exit 0
done
